name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - id: modified
        name: path-watcher-action
        uses: pheel/path-watcher-action@v1
        with:
          paths: '7semestrPLT/*'
      - if: steps.modified.outputs.modified
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run tests
        run: sbt test
